export const GET_CITIES_REQUEST = 'GET_CITIES_REQUEST';
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS';
export const GET_CITIES_FAILURE = 'GET_CITIES_FAILURE';

export const SAVE_SELECTED_CITY = 'SAVE_SELECTED_CITY';
export const REPLACE_SELECTED_CITY = 'REPLACE_SELECTED_CITY';
export const ADD_NEW_CITY = 'ADD_NEW_CITY';
export const REMOVE_CURRENT_CITY = 'REMOVE_CURRENT_CITY';

export const INIT_SELECTED_CITY = 'INIT_SELECTED_CITY';
export const SET_FAVORITES_CITIES = 'SET_FAVORITES_CITIES';

export const CLEAR_STATE = 'CLEAR_STATE';
